import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import {
  requirePhase012Preflight,
  requirePhase012Generation,
  requirePhase012FailureChain,
  createPhase012RetryPlan,
  requirePhase012ImplementationBinding,
} from "../../docs/phase-plans/phase012-evidence.mjs";
import {
  requireHashCoverage,
  requireReportBinding,
  requirePriorCaseBinding,
} from "../../scripts/phase-evidence.mjs";
import {
  command,
  scanSensitiveText,
  safeDiagnostics,
} from "../../docs/phase-plans/phase012-runtime.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const digest = (bytes) => createHash("sha256").update(bytes).digest("hex");
const readText = (file) => fs.readFileSync(path.join(root, file), "utf8");
const readJson = (file) => JSON.parse(readText(file));
const hashFile = (file) => digest(fs.readFileSync(path.join(root, file)));
const planPath = "docs/phase-plans/Phase012.json";
const plan = readJson(planPath);
const receipt = readJson("docs/phase-plans/Phase012-inputs.json");
const generation = readJson(
  plan.migrationPolicy.preparedReceiptPath ?? plan.migrationPolicy.generationReceiptPath,
);
const dependencies = {
  receipt,
  hashFile,
  readText,
  migrationPath: generation.generatedMigrationPath,
};
const results = [];

function check(name, operation) {
  operation();
  results.push({ name, status: "PASS" });
}

check("actual admission binds both distinct successful shells and the synchronized metadata", () =>
  requirePhase012Preflight(receipt.preflight),
);
for (const [name, change] of [
  [
    "missing-shell",
    (value) => {
      value.shells.pop();
    },
  ],
  [
    "duplicate-shell",
    (value) => {
      value.shells[1] = value.shells[0];
    },
  ],
  [
    "failed-shell",
    (value) => {
      value.shells[0].exitCode = 1;
    },
  ],
  [
    "wrong-phase",
    (value) => {
      value.phase = 9;
    },
  ],
  [
    "dirty-tree",
    (value) => {
      value.workingTree = " M source";
    },
  ],
  [
    "wrong-metadata",
    (value) => {
      value.shells[0].result.metadataCommit = "0".repeat(40);
    },
  ],
  [
    "unsynchronized-origin",
    (value) => {
      value.originMain = "0".repeat(40);
    },
  ],
])
  check(`reject admission ${name}`, () => {
    const changed = structuredClone(receipt.preflight);
    change(changed);
    assert.throws(() => requirePhase012Preflight(changed));
  });

check("actual migration binds original generated SQL, all six earlier migrations and schema", () =>
  requirePhase012Generation(generation, dependencies),
);
for (const [name, change] of [
  [
    "changed-migration-hash",
    (value) => {
      value.migrationHash = "0".repeat(64);
    },
  ],
  [
    "changed-raw-hash",
    (value) => {
      value.rawMigrationHash = "0".repeat(64);
    },
  ],
  [
    "changed-schema-hash",
    (value) => {
      value.schemaHash = "0".repeat(64);
    },
  ],
  [
    "missing-generation-command",
    (value) => {
      value.records = [];
    },
  ],
  [
    "duplicate-generation-command",
    (value) => {
      value.records.push(
        value.records.find((record) => record.arguments?.includes("--create-only")),
      );
    },
  ],
  [
    "failed-generation",
    (value) => {
      value.records.find((record) => record.arguments?.includes("--create-only")).exitCode = 1;
    },
  ],
  [
    "timed-out-generation",
    (value) => {
      value.records.find((record) => record.arguments?.includes("--create-only")).timedOut = true;
    },
  ],
  [
    "missing-earlier-migration",
    (value) => {
      value.previousMigrations.pop();
    },
  ],
  [
    "changed-protection-hash",
    (value) => {
      value.protectionHash = "0".repeat(64);
    },
  ],
])
  check(`reject migration ${name}`, () => {
    const changed = structuredClone(generation);
    change(changed);
    assert.throws(() => requirePhase012Generation(changed, dependencies));
  });
check("reject migration whose applied SQL no longer begins with its generated bytes", () => {
  assert.throws(() =>
    requirePhase012Generation(generation, {
      ...dependencies,
      readText: (file) =>
        file === generation.generatedMigrationPath ? "different SQL" : readText(file),
    }),
  );
});

check("migration protection cannot be replaced by another source", () => {
  const changed = structuredClone(generation);
  changed.protectionPath = "docs/phase-plans/api-key-config-protection.sql";
  changed.protectionHash = hashFile(changed.protectionPath);
  assert.throws(() => requirePhase012Generation(changed, dependencies));
});

check("actual previous failure chain is complete and immutable", () =>
  requirePhase012FailureChain(plan, { readJson, hashFile }),
);
check("retry freezes each failed attempt without replacing its plan or failure", () => {
  const first = { ...structuredClone(plan), attemptId: "attempt-1", previousAttempts: [] };
  const frozenPath = "docs/evidence/attempts/Phase012/attempt-1/frozen-plan.json";
  const failurePath = "docs/evidence/attempts/Phase012/attempt-1/attempt.json";
  const files = new Map([[frozenPath, JSON.stringify(first)]]);
  files.set(
    failurePath,
    JSON.stringify({
      phase: 12,
      attemptId: "attempt-1",
      status: "FAIL",
      artifactCommit: null,
      planHash: digest(files.get(frozenPath)),
    }),
  );
  const readers = {
    readJson: (file) => JSON.parse(files.get(file)),
    hashFile: (file) => digest(files.get(file)),
  };
  const next = createPhase012RetryPlan(first, readers);
  assert.equal(next.attemptId, "attempt-2");
  assert.deepEqual(next.requiredCaseIds, first.requiredCaseIds);
  assert.equal(next.previousAttempts[0].planHash, readers.hashFile(frozenPath));
  assert.equal(next.previousAttempts[0].failureHash, readers.hashFile(failurePath));
  for (const change of [
    (value) => {
      value.previousAttempts = [];
    },
    (value) => {
      value.previousAttempts[0].failureHash = "0".repeat(64);
    },
    (value) => {
      value.previousAttempts[0].planHash = "0".repeat(64);
    },
    (value) => {
      value.previousAttempts[0].failurePath = "different.json";
    },
    (value) => {
      value.previousAttempts.push(value.previousAttempts[0]);
    },
  ]) {
    const changed = structuredClone(next);
    change(changed);
    assert.throws(() => requirePhase012FailureChain(changed, readers));
  }
  files.set(
    failurePath,
    JSON.stringify({
      phase: 12,
      attemptId: "attempt-1",
      status: "PASS",
      artifactCommit: null,
      planHash: readers.hashFile(frozenPath),
    }),
  );
  next.previousAttempts[0].failureHash = readers.hashFile(failurePath);
  assert.throws(() => requirePhase012FailureChain(next, readers));
});

check(
  "all current cases preserve the original required commands, denominators and expectations",
  () => {
    for (const previous of plan.previousAttempts)
      requirePriorCaseBinding(plan, readJson(previous.planPath), { readJson, hashFile });
  },
);
for (const [name, change] of [
  [
    "removed-case",
    (value) => {
      value.cases.pop();
    },
  ],
  [
    "changed-command",
    (value) => {
      value.cases[0].command = "echo success";
    },
  ],
  [
    "changed-input",
    (value) => {
      value.cases[0].inputPath = "different.ts";
    },
  ],
  [
    "reduced-denominator",
    (value) => {
      value.cases[0].denominator = 0;
    },
  ],
  [
    "weaker-expectation",
    (value) => {
      value.cases[0].expected = "Only some cases need pass.";
    },
  ],
])
  check(`reject prior-case ${name}`, () => {
    const changed = structuredClone(plan);
    change(changed);
    assert.throws(() =>
      requirePriorCaseBinding(changed, readJson(plan.previousAttempts[0].planPath), {
        readJson,
        hashFile,
      }),
    );
  });

const item = plan.cases[0];
const sourceHashes = Object.fromEntries(plan.sourcePaths.map((file) => [file, hashFile(file)]));
const report = {
  testCaseId: item.testCaseId,
  command: item.command,
  status: "PASS",
  exitCode: 0,
  numerator: item.denominator,
  denominator: item.denominator,
  inputPath: item.inputPath,
  inputHash: hashFile(item.inputPath),
  planHash: hashFile(planPath),
  sourceHashes,
};
check("synthetic evidence-only fixture verifies exact source and frozen case bindings", () =>
  requireReportBinding(report, item, hashFile(planPath), plan.sourcePaths, hashFile),
);
for (const field of [
  "testCaseId",
  "command",
  "status",
  "exitCode",
  "numerator",
  "denominator",
  "inputPath",
  "inputHash",
  "planHash",
])
  check(`reject report changed ${field}`, () => {
    const changed = structuredClone(report);
    changed[field] = typeof changed[field] === "number" ? 999 : "changed";
    assert.throws(() =>
      requireReportBinding(changed, item, hashFile(planPath), plan.sourcePaths, hashFile),
    );
  });
for (const [name, change] of [
  [
    "missing-source",
    (value) => {
      delete value[plan.sourcePaths[0]];
    },
  ],
  [
    "extra-source",
    (value) => {
      value["not-an-input.ts"] = "1".repeat(64);
    },
  ],
  [
    "changed-source",
    (value) => {
      value[plan.sourcePaths[0]] = "0".repeat(64);
    },
  ],
])
  check(`reject hash binding ${name}`, () => {
    const changed = structuredClone(sourceHashes);
    change(changed);
    assert.throws(() =>
      requireHashCoverage(changed, plan.sourcePaths, hashFile, "TEST_HASH_BINDING"),
    );
  });

check(
  "implementation contents, added files and removed files all invalidate earlier verification",
  () => {
    const before = { "src/a.ts": "1".repeat(64), "tests/a.ts": "2".repeat(64) };
    requirePhase012ImplementationBinding(before, { ...before });
    assert.throws(() =>
      requirePhase012ImplementationBinding(before, { ...before, "src/a.ts": "3".repeat(64) }),
    );
    assert.throws(() =>
      requirePhase012ImplementationBinding(before, { ...before, "src/b.ts": "3".repeat(64) }),
    );
    assert.throws(() =>
      requirePhase012ImplementationBinding(before, { "src/a.ts": "1".repeat(64) }),
    );
  },
);

check("safe output retains a positive scan-before-redaction receipt", () => {
  assert.deepEqual(scanSensitiveText("safe synthetic summary"), {
    hits: 0,
    scannedBeforeRedaction: true,
  });
  assert.equal(safeDiagnostics("safe synthetic summary"), "safe synthetic summary");
});
for (const [name, value] of [
  ["provider-pattern", ["sk", "X".repeat(32)].join("-")],
  [
    "serialized-envelope",
    JSON.stringify({
      algorithm: "A256GCM",
      ciphertext: Buffer.from("synthetic fixture").toString("base64"),
    }),
  ],
  [
    "nested-serialized-envelope",
    JSON.stringify({
      nested: JSON.stringify({ ciphertext: Buffer.from("synthetic fixture").toString("base64") }),
    }),
  ],
  [
    "credential-url",
    new URL(
      "postgresql:" + "//" + ["fixture", "fixture"].join(":") + "@127.0.0.1:5432/disposable",
    ).toString(),
  ],
])
  check(`reject raw ${name} before archival without echo`, () => {
    assert.throws(() => scanSensitiveText(value), /SECRET_SCAN_REJECTED/);
    const safe = safeDiagnostics(value);
    assert.equal(safe, "Diagnostics withheld: raw secret scan rejected the output.");
    assert(!safe.includes(value));
  });
await assert.rejects(
  command("Raw-output leak rejection probe", [
    "--input-type=module",
    "-e",
    'process.stdout.write(["sk", "X".repeat(32)].join("-"))',
  ]),
  /SECRET_SCAN_REJECTED/,
);
results.push({
  name: "real child output leak cannot become a successful command receipt",
  status: "PASS",
});

const testedPaths = [
  "docs/phase-plans/phase012-evidence.mjs",
  "docs/phase-plans/phase012-runtime.mjs",
  "scripts/phase-evidence.mjs",
  "tests/phase012/evidence-guards.mjs",
];
const output = {
  status: "PASS",
  phase: 12,
  results,
  caseCount: results.length,
  testedSourceHashes: Object.fromEntries(testedPaths.map((file) => [file, hashFile(file)])),
  scope: "EVIDENCE_REJECTION_REGRESSION_NOT_PRODUCT_MOCK",
};
const argument = process.argv.indexOf("--output");
if (argument !== -1) {
  const target = path.resolve(process.argv[argument + 1]);
  assert(target.startsWith(path.join(root, ".scaffold/phase012") + path.sep));
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(output, null, 2) + "\n", { flag: "wx" });
}
console.warn(JSON.stringify({ status: output.status, caseCount: output.caseCount }));
